# Generated by Django 3.2.6 on 2021-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=25)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Female', max_length=10)),
                ('age', models.IntegerField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
